### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: No AppBrainJobService defined in the manifest!

### ISSUE THREAD

**Issue by cico1980** [swisscodemonkeys/appbrain-sdk#14]
Android version 4.3, sdk 16:

Fatal Exception: java.lang.IllegalStateException: No AppBrainJobService defined in the manifest!
       at com.appbrain.a.n1$c.run()
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)

**Comment by bizire** [comment]
I have the same issue on Android 4.4.2 . Sdk 17. Appbrain Version V16.00 - IllegalStateException: No AppBrainJobService defined in the manifest.

On new Android such as Android 9.0 everything is good with v16.00
With AppBrain 15.11 everything is OK on Android 4.4.2.

**Comment by cico1980** [comment]
I also tried with version 15.11 on Sdk 16, it always gives me the same error.

**Comment by mathijs81** [comment]
Sorry about this, I will release version 16.01 that fixes this.
