### ISSUE TITLE
 Clash of Clans

### ISSUE THREAD

**Issue by Trackcourier22** [swisscodemonkeys/appbrain-sdk#17]
I cant believe I found this just now: http://clashofclanshelper.com/) - you receive free Clash of Clans gems instantly! Everybody uses this [now](https://trackcourier.pk/call-courier-tracking-pakistan/)! (IzozRftDa4)

**Comment by captianben** [comment]
Ok dear let me [see](https://playbadicecream.com/bad-ice-cream-3/)
