### ISSUE TITLE
Click on in app banner does not work.

### ISSUE THREAD

**Issue by xproph** [swisscodemonkeys/appbrain-sdk#2]
On the previous version (10.4) when clicking on "More apps" or "Download apps" buttons in the banner it was showing the App wall. On the new version it does not do anything.

**Comment by mathijs81** [comment]
The banners work as expected in the example app that comes with the SDK on my device (Nexus 5). Do you get any adb logcat warning? Do you add the banner through XML or programmatically?
Please email us on contact@appbrain.com and we can resolve this issue.

**Comment by xproph** [comment]
Fixed in the new patch 10.51.
