### ISSUE TITLE
Maven repo gives 404

### ISSUE THREAD

**Issue by amr** [swisscodemonkeys/appbrain-sdk#4]
The repo URL http://swisscodemonkeys.github.io/appbrain-sdk/maven currently returns 404

**Comment by uwemaurer** [comment]
This URL indeed gives 404, however it works fine as a gradle repository (gradle uses this as base url and looks into sub directories)

Please add it like this to your `build.gradle` file: 
```
repositories {
    maven {
        url 'http://swisscodemonkeys.github.io/appbrain-sdk/maven'
    }
}

dependencies {
    compile 'com.appbrain:appbrain-applift-sdk:+'
}
```

Please see here for more information how to integrate the SDK: http://www.appbrain.com/info/help/sdk/gettingstarted.html

**Comment by uwemaurer** [comment]
I added an index file to prevent this 404
